# Generated by Django 3.2.5 on 2021-07-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(default='image', null=True, upload_to='pictures/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictorial.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictorial.location')),
            ],
        ),
    ]
