# Generated by Django 3.2.5 on 2021-07-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictorial', '0002_auto_20210703_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_name']},
        ),
    ]
