# Generated by Django 3.2.5 on 2021-07-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictorial', '0003_alter_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='image', upload_to='pictures/'),
        ),
    ]
