# Generated by Django 3.2.5 on 2021-07-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictorial', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
